### ISSUE TITLE
Hyperbolic visualization on Poincare disk

### ISSUE THREAD

**Issue by jiawen-zhu** [ChengHan111/E2VPT#2]
Dear authors, nice work！

I'm interested in the hyperbolic visualization results on Poincare disk in Figure 3.
Can you share the tool code or tell me how to draw the figure?
Much thanks.

**Comment by ChengHan111** [comment]
Hi, 

Thank you for your interests to our work! We are sorry that we do not have a plan for releasing this part due to the concurrent heavy workload. However, we apply this idea from the paper [CVPR2022] "Hyperbolic Vision Transformers: Combining Improvements in Metric Learning". They have publicly released their code.  Please kindly consider citing our paper if you find it beneficial or relevant to your work.

Thanks.

**Comment by jiawen-zhu** [comment]
Okay, thanks for your suggestion~

**Comment by ChengHan111** [comment]
I am closing this issue since no more updates are needed for now. Thank you!

**Comment by ChengHan111** [comment]
I am closing this issue since no more updates are needed for now. Thank you!
