### ISSUE TITLE
Cannot find appendix

### ISSUE THREAD

**Issue by GrantorShadow** [ChengHan111/E2VPT#3]
Dear Authors,
Thank you for your contribution. I was wondering if you could give me a link to the appendix of the paper, as I wished to tabulate the FGVC and Vtab 1k results in terms of individual performance on each dataset.
Thank you for your time

**Comment by ChengHan111** [comment]
Hi Thank you for your interest to our paper. I think the ICCV committee would release both the formal version of paper and appendix sooner or later. Currently we do not have a plan to push another version to arxiv (since the appendix is separated from the paper). But we do believe it would come out soon. However, I do able to screenshot some of the results FYI. All results from ViT-Base/16. If you find our paper useful, please consider to cite! Thank you. 
![image](https://github.com/ChengHan111/E2VPT/assets/59878469/d02e081b-01a2-4d14-a087-d45d15dad0df)
![image](https://github.com/ChengHan111/E2VPT/assets/59878469/3f49b9bc-e16d-4647-8209-b0926b30efa0)
![image](https://github.com/ChengHan111/E2VPT/assets/59878469/b7abbd6a-e395-4436-bb85-b8a5fba14d98)
![image](https://github.com/ChengHan111/E2VPT/assets/59878469/85f0d347-6bb1-4d9c-8fdd-82888e6d7465)

**Comment by GrantorShadow** [comment]
@ChengHan111 Thank you for your reply. 

Could you please elaborate on the training objective used in this implementation? Specifically, I'm interested to know whether MAE, MoCo V3, or a Supervised Learning approach was followed. I'd also like to confirm that the results you've shared can be replicated by executing the commands listed in command.txt.

**Comment by ChengHan111** [comment]
We follow the original implementation in VPT and use a supervised learning approach while only changing the pretrain learning objectives into MAE and MoCo V3 model. The results are as follows. 
![image](https://github.com/ChengHan111/E2VPT/assets/59878469/1a8df2c4-1360-4c89-afea-ffb39ae45fe6)
![image](https://github.com/ChengHan111/E2VPT/assets/59878469/f446e808-2551-4161-95f4-07e955a4094a)
![image](https://github.com/ChengHan111/E2VPT/assets/59878469/4ae0db6d-824c-41ae-8b3c-33a91415f0f4)
